// Test generated by RoostGPT for test knote-java using AI Type Open AI and AI Model gpt-4

package org.aws.samples.greeting;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;

@SpringBootTest
public class GreetingController_sayHello_26998730d5_Test {

    @MockBean
    private GreetingController greetingController;

    @BeforeEach
    public void setUp() {
        Mockito.when(greetingController.sayHello()).thenReturn("Hello");
    }

    @Test
    public void testSayHello() {
        String result = greetingController.sayHello();
        Assertions.assertEquals("Hello", result, "Expected and actual results do not match");
    }

    @Test
    public void testSayHelloFailure() {
        Mockito.when(greetingController.sayHello()).thenReturn("Hi");
        String result = greetingController.sayHello();
        Assertions.assertNotEquals("Hello", result, "Expected and actual results should not match");
    }
}
